[package]
name = "fast_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = "0.1.18"
colored = "2.1"
cranelift = "0.134.3"
cranelift-module = "0.134.3"
cranelift-jit = "0.134.3"
cranelift-object = "0.134.3"
cranelift-frontend = "0.134.3"
cranelift-codegen = "0.134.3"
cranelift-native = "0.134.3"
